"""
SGLang PR Review Orchestrator

This module is designed to be used by Claude Code as a skill.
It provides functions to:
1. Fetch a PR (diff, files, description)
2. Route to domain experts
3. Format review results

Usage from Claude Code:
  The skill prompt in SKILL.md instructs Claude Code to:
  - Use `gh` CLI to fetch PR data
  - Import router.py to determine experts
  - Read expert prompts and use them as system context for sub-agent reviews
  - Aggregate results and post as a comment
"""

import json
import os
import sys

# Add this directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from router import route_pr, get_expert_prompt, format_routing_summary, get_expert_description


def parse_pr_url(pr_ref: str) -> tuple[str, str, int]:
    """
    Parse a PR reference into (owner, repo, pr_number).
    Accepts:
      - Full URL: https://github.com/sgl-project/sglang/pull/1234
      - Short: 1234 (defaults to sgl-project/sglang)
      - owner/repo#1234
    """
    import re

    # Full GitHub URL
    url_match = re.match(
        r"https?://github\.com/([^/]+)/([^/]+)/pull/(\d+)", pr_ref
    )
    if url_match:
        return url_match.group(1), url_match.group(2), int(url_match.group(3))

    # owner/repo#number
    short_match = re.match(r"([^/]+)/([^#]+)#(\d+)", pr_ref)
    if short_match:
        return short_match.group(1), short_match.group(2), int(short_match.group(3))

    # Just a number (default to sgl-project/sglang)
    if pr_ref.strip().isdigit():
        return "sgl-project", "sglang", int(pr_ref.strip())

    raise ValueError(
        f"Cannot parse PR reference: {pr_ref}. "
        "Use a full URL, owner/repo#number, or just a PR number."
    )


def format_expert_review_prompt(expert_name: str, pr_title: str, pr_body: str,
                                 diff: str, changed_files: list[str]) -> str:
    """
    Build the full prompt for a domain expert to review a PR.
    """
    expert_prompt = get_expert_prompt(expert_name)
    desc = get_expert_description(expert_name)

    files_list = "\n".join(f"  - {f}" for f in changed_files)

    return f"""{expert_prompt}

---

## PR Under Review

**Title**: {pr_title}
**Description**:
{pr_body}

**Changed files**:
{files_list}

**Diff**:
```diff
{diff}
```

---

## Your Task

Review this PR from your domain perspective ({desc}).

Provide your review in the following format:

### {expert_name} Review

**Risk Level**: [Low / Medium / High / Critical]

**Summary**: 1-2 sentence summary of your findings.

**Issues Found** (if any):
- [Issue description, file:line if applicable, severity]

**Suggestions** (if any):
- [Suggestion description]

**Looks Good** (if applicable):
- [What aspects are well-implemented from your domain perspective]

Keep your review concise and focused on your domain. If the PR doesn't significantly touch your domain, say so briefly.
"""


def format_aggregated_review(expert_reviews: dict[str, str],
                              routing_summary: str,
                              pr_title: str) -> str:
    """
    Aggregate all expert reviews into a single formatted comment.
    """
    parts = [
        f"# 🔍 SGLang Domain Expert Review",
        f"**PR**: {pr_title}\n",
        routing_summary,
        "\n---\n",
    ]

    for expert_name, review in expert_reviews.items():
        parts.append(review)
        parts.append("\n---\n")

    parts.append(
        "\n*This review was generated by SGLang domain expert agents. "
        "Each expert focuses on their area of the codebase. "
        "Please address any High/Critical issues before merging.*"
    )

    return "\n".join(parts)


# CLI usage for testing
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python review.py <PR_URL_or_NUMBER>")
        print("Example: python review.py https://github.com/sgl-project/sglang/pull/1234")
        sys.exit(1)

    owner, repo, pr_num = parse_pr_url(sys.argv[1])
    print(f"Parsed: {owner}/{repo}#{pr_num}")
    print("Use this with Claude Code's /review-sglang-pr skill for full functionality.")
